print(" ")
print('                    " PROGRAM TO CONVERT TIME "')
print(" ")
print("Select Operation!")
print(" ")
print("1. Seconds to Minutes,Hour,Day")
print(" ")
print("2. Minutes to Seconds,Hour,Day")
print(" ")
print("3. Hour to Second,Minutes,Day")
print(" ")
print("4. Day to Seconds,Minutes,Hour")
print(" ")

choice = int(input("Enter Choice(1/2/3/4): "))

if choice == 1:
    print(" ")
    time1 = float(input("Enter Seconds: "))
    print(" ")
    ans1 = (time1/60)
    ans2 = (time1/3600)
    ans3 = (time1/86400)
    print( str(time1) + " Seconds is Equal To " + str(ans1) + " Minutes")
    print(" ")
    print( str(time1) + " Seconds is Equal To " + str(ans2) + " Hours")
    print(" ")
    print( str(time1) + " Seconds is equal To " + str(ans3) + " Days")
    print(" ")

elif choice == 2:
    print(" ")
    time2 = float(input("Enter Minutes: "))
    print(" ")
    asn1 = (time2 * 60)
    asn2 = (time2 / 60)
    asn3 = (time2 / 1440)
    print( str(time2) + " Minutes is Equal To " + str(asn1) + " Seconds")
    print(" ")
    print( str(time2) + " Minutes is Equal To " + str(asn2) + " Hours")
    print(" ")
    print( str(time2) + " Minutres is equal To " + str(asn3) + " Days")
    print(" ")

elif  choice == 3:
    print(" ")
    time3 = float(input("Enter Hours: "))
    print(" ")
    anss1 = (time3 * 3600)
    anss2 = (time3 * 60)
    anss3 = (time3 / 24)
    print( str(time3) + " Hours is Equal To " + str(anss1) + " Seconds")
    print(' ')
    print( str(time3) + " Hours is Equal To " + str(anss2) + " Minutes")
    print(" ")
    print( str(time3) + " Hours is Equal To " + str(anss3) + " Day")
    print(" ")

elif choice == 4:
    print(" ")
    time4 = float(input("Enter Days: "))
    print(" ")
    aasn1 = (time4 * 86400)
    aasn2 = (time4 * 1440)
    aasn3 = (time4 * 24)
    print( str(time4) + " Days is Equal To " + str(aasn1) + " Seconds")
    print(" ")
    print( str(time4) + " Day is Equal To " + str(aasn2) + " Minutes")
    print(" ")
    print( str(time4) + " Days is Equal To " + str(aasn3) + " Hour")
    print(" ")

else:
    print(" ")
    print("Invalid Input")
    print(' ')